version: "3.1"

services:
  db:
    image: postgres:13
    container_name: invoice_container
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: admin123
      POSTGRES_DB: invoice_db
    volumes:
      - ./db_data:/var/lib/postgresql/data
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
    ports:
      - "5432:5432"
    networks:
      - backend

  pg_admin:
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: test@gmail.com
      PGADMIN_DEFAULT_PASSWORD: admin
    ports:
      - 5050:80
    networks:
      - backend

  api:
    build: .
    environment:
      DB_HOST: db
      DB_USER: postgres
      DB_PASSWORD: admin123
      DB_NAME: invoice_db
    ports:
      - "3000:3000"
    depends_on:
      - db
    networks:
      - backend

volumes:
  db_data:

networks:
  backend:
    driver: bridge
